homeview/urls.py
from django.contrib import admin  
from django.urls import path  
from homeview import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),
    path('',views.login),  
    path('signin', views.signin),
    path('signout', views.signout),
    path('main', views.main),
    path('file_upload', views.file_upload),
    path('log_history', views.log_history),
    path('create_user', views.create_user),
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
    path('detector', views.detector),
    path('trainmodel', views.trainmodel),
    path('clearmodel', views.clearmodel),
    path('getmessage1', views.getmessage1),
    path('getmessage2', views.getmessage2),
]  

iotbotnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeview.urls'))
]

homeview/models.py
from django.db import models

# Create your models here.
class LogHistory(models.Model):  
    logid = models.CharField(max_length=20)  
    logname = models.CharField(max_length=100)  
    logdate = models.CharField(max_length=15) 
    logstate = models.CharField(max_length=15)  
    class Meta:  
        db_table = "loghistory"  

class User(models.Model):
    """Model definition for User."""

    # TODO: Define fields here
    id = models.IntegerField(max_length=255, primary_key=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=255)
    role = models.IntegerField(max_length=1)
    class Meta:
        """Meta definition for User."""

        db_table = "users"

homeview/forms.py
from django import forms  
from homeview.models import LogHistory, User
class LogHistoryForm(forms.ModelForm):  
    class Meta:  
        model = LogHistory  
        fields = "__all__"  

class UserForm(forms.ModelForm):
    """Form definition for User."""

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = ['username', 'password', 'role']

homeview/views.py
from django.shortcuts import render, redirect  
from homeview.forms import LogHistoryForm, UserForm
from homeview.models import LogHistory
from django.contrib import messages  
from django.utils.functional import cached_property
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from django.core.files.storage import FileSystemStorage
import sys
import Phase1.phaseOneProcessor as phaseOne
import Phase2.phaseTwoProcessor as phaseTwo
import os
from django.http import HttpResponse
import json
from datetime import datetime

def create_user(request):
    username = request.GET.get('username')
    password = request.GET.get('password')
    email = request.GET.get('email')
    user = User.objects.create_user('SystemAdmin', 'SystemAdmin@gmail.com', 'root')
    user.is_staff = '2'
    user.save()
def emp(request):  
    if request.method == "POST":  
        form = LogHistoryForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = LogHistoryForm()  
    return render(request,'index.html',{'form':form}) 

def login(request):
    if request.user.is_authenticated:
        return redirect('/main')
    else:
        return render(request, 'login.html')
def signin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request)
        request.session['username'] = username
        request.session['role'] = user.is_staff
        request.session['email'] = user.email
        if request.session['role'] == 1 or request.session['role'] == 2:
            return redirect('/main')
        if request.session['role'] == 3:
            return redirect('/log_history')
        else:
            messages.success(request, 'Your account is not yet activated.')
            return redirect('/')

    else:
        messages.success(request, 'Please enter your username and password exactly.')
        return redirect('/')
def signout(request):
    logout(request)
    return redirect('/')
def main(request):
    if request.session['role'] == 1 or request.session['role'] == 2:
        return render(request, 'main.html')
    else:
        return redirect('/log_history')
def file_upload(request):
    myfile = request.FILES['file']
    fs = FileSystemStorage()
    filename = fs.save(myfile.name, myfile)
    uploaded_file_url = fs.url(filename)
    return HttpResponse({uploaded_file_url : uploaded_file_url})
def log_history(request):
    if request.session['role'] == 1 or request.session['role'] == 3:
        loghistoryAll = LogHistory.objects.all()  
        return render(request, 'log_history.html', {'loghistoryAll':loghistoryAll})
    else:
        return redirect('/main')
def show(request):  
    loghistoryAll = LogHistory.objects.all()  
    return render(request,"show.html",{'loghistoryAll':loghistoryAll})  
def edit(request, id):  
    logbyid = LogHistory.objects.get(id=id)  
    return render(request,'edit.html', {'logbyid':logbyid})  
def update(request, id):  
    logbyid = LogHistory.objects.get(id=id)  
    form = LogHistoryForm(request.POST, instance = logbyid)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'logbyid': logbyid})  
def destroy(request, id):  
    logbyid = LogHistory.objects.get(id=id)  
    logbyid.delete()  
    return redirect("/show")  
# trainmodel
def trainmodel(request):
    strReturnMsg,strStatusMsg = phaseOne.beginTrain()
    responseData = {
        
        'message': strReturnMsg,
        'status':strStatusMsg
    }
    return HttpResponse(json.dumps(responseData), content_type="application/json")
# clear the trainmodel
def clearmodel(request):
    strReturnMsg = "Success"
    for idx in range(8):
        Pkl_Filename = f'ml_model/Pickle_RL_Model{idx+1}.pkl' 
        os.remove(Pkl_Filename)

    responseData = {
        
        'message': strReturnMsg
        
    }
    return HttpResponse(json.dumps(responseData), content_type="application/json")  

# Create your tests here.
def detector(request):  
    pcappath = request.POST['path']
    pcappath = pcappath.split("\\")[-1]
    strReturnMsg, stateValue = phaseTwo.beginTestforAttack(pcappath)
    
    strtoday = datetime.today().strftime('%Y-%m-%d-%H:%M:%S')
    if(stateValue == 0 or stateValue == -1):
        strResult = ""
        if(stateValue == 0):
            strResult = "Normal"
        if(stateValue == -1):
            strResult = "Abnormal"
        #    strResult,pcappath,strtoday
        logsave = LogHistory()
        logsave.logid = 7
        logsave.logdate = strtoday
        logsave.logname = pcappath
        logsave.logstate = strResult
        logsave.save()
    responseData = {
        
        'message': strReturnMsg,
        'state' : stateValue
    }

    return HttpResponse(json.dumps(responseData), content_type="application/json")  

def getmessage1(request):
    path = "./homeview/static/message/phase1_output.ms"
    message_file = open(path, "r")
    data = message_file.read()
    responseData = {
        
        'message': data,
        'state' : "success"
    }

    return HttpResponse(json.dumps(responseData), content_type="application/json")
    
def getmessage2(request):
    path = "./homeview/static/message/phase2_output.ms"
    message_file = open(path, "r")
    data = message_file.read()
    responseData = {
        
        'message': data,
        'state' : "success"
    }

    return HttpResponse(json.dumps(responseData), content_type="application/json")

homeview/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{logbyid.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label"> Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="logid" id="id_logid" required maxlength="20" value="{{ logbyid.logid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">File Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="logname" id="id_logname" required maxlength="100" value="{{ logbyid.logname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Log Date:</label>  
    <div class="col-sm-4">  
        <input type="text" name="logdate" id="id_logdate" required maxlength="254" value="{{ logbyid.logdate }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Log State:</label>  
    <div class="col-sm-4">  
        <input type="text" name="logstate" id="id_logstate" required maxlength="15" value="{{ logbyid.logstate }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

homeview/templates/homeview.html
<h1>Hello, World!</h1>

homeview/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Id:</label>  
    <div class="col-sm-4">  
      {{ form.logid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">File Name:</label>  
    <div class="col-sm-4">  
      {{ form.logname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Log Date:</label>  
    <div class="col-sm-4">  
      {{ form.logdate }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Log State:</label>  
    <div class="col-sm-4">  
      {{ form.logstate }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

homeview/templates/login.html
<!DOCTYPE html>
<html lang="en">
	<!--begin::Head-->
	<head>
		<meta charset="utf-8" />
		<title>BotNet | Login</title>
		{% load static %}
		<meta name="description" content="Login page example" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="canonical" href="https://keenthemes.com/metronic" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Page Custom Styles(used by this page)-->
		<link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Page Custom Styles-->
		<!--begin::Global Theme Styles(used by all pages)-->
		<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Global Theme Styles-->
		<!--begin::Layout Themes(used by all pages)-->
		<!--end::Layout Themes-->
		<link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}" />
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body id="kt_body" style="background-image: url({% static 'assets/media/bg/bg-10.jpg' %});" class="quick-panel-right demo-panel-right offcanvas-right header-fixed subheader-enabled page-loading">
		<!--begin::Main-->
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			<div class="login login-5 login-signin-on d-flex flex-row-fluid" id="kt_login">
				<div class="d-flex flex-center bgi-size-cover bgi-no-repeat flex-row-fluid" style="background-image: url({% static 'assets/media/bg/bg-2.jpg' %});">
					<div class="login-form text-center text-white p-7 position-relative overflow-hidden">
						<!--begin::Login Header-->
						<div class="d-flex flex-center mb-15">
							<a href="#">
								<!-- <h3 class="opacity-40 font-weight-normal">IoT Botnet Detection</h3> -->
							</a>
						</div>
						<!--end::Login Header-->
						<!--begin::Login Sign in form-->
						<div class="login-signin">
							<div class="mb-20">
								<h1 class="opacity-40 font-weight-normal">IoT Botnet Detection</h1>
								<p class="opacity-40">Enter your details to login to your account:</p>
							</div>
							{% if messages %}
								{% for message in messages %}
								<div class="alert alert-custom alert-notice alert-light-danger fade show" role="alert">
									<div class="alert-icon"><i class="flaticon-warning"></i></div>
									<div class="alert-text">{{ message }}</div>
									<div class="alert-close">
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
											<span aria-hidden="true"><i class="ki ki-close"></i></span>
										</button>
									</div>
								</div>
								{% endfor %}
							{% endif %}
							
							<form class="form" id="kt_login_signin_form" action="/signin" method="POST">
								{% csrf_token %}
								<div class="form-group">
									<input class="form-control h-auto text-white bg-white-o-5 rounded-pill border-0 py-4 px-8" type="text" placeholder="Username" name="username" autocomplete="off" />
								</div>
								<div class="form-group">
									<input class="form-control h-auto text-white bg-white-o-5 rounded-pill border-0 py-4 px-8" type="password" placeholder="Password" name="password" />
								</div>
								<div class="form-group text-center mt-10">
									<button id="kt_login_signin_submit" type="submit" class="btn btn-pill btn-primary opacity-90 px-15 py-3">Sign In</button>
								</div>
							</form>
						</div>
						<!--end::Login Sign in form-->
					</div>
				</div>
			</div>
			<!--end::Login-->
		</div>
		<!--end::Main-->
		<script>var HOST_URL = "https://preview.keenthemes.com/metronic/theme/html/tools/preview";</script>
		<!--begin::Global Config(global config for global JS scripts)-->
		<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#6993FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1E9FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
		<!--end::Global Config-->
		<!--begin::Global Theme Bundle(used by all pages)-->
		<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
		<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
		<!--end::Global Theme Bundle-->
		<!--begin::Page Scripts(used by this page)-->
		<script src="{% static 'js/login.js' %}"></script>
		<!--end::Page Scripts-->
	</body>
	<!--end::Body-->
</html>

homeview/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Log History</title>  
    <meta name="viewport" content="width=device-width, initial-scale=1">
     {% load static %} 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    

</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th> ID</th>  
        <th>File Name</th>  
        <th>Log Date</th>  
        <th>Log State</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for log in loghistoryAll %}  
    <tr>  
        <td>{{ log.logid }}</td>  
        <td>{{ log.logname }}</td>  
        <td>{{ log.logdate }}</td>  
        <td>{{ log.logstate }}</td>  
        <td>  
            <a href="/edit/{{ log.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ log.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  